apiVersion: v1
kind: Service
metadata:
  name: "v4-c6m03-attempt0229-ba273a28f8-policy"
  namespace: "211247-prod"
  labels:
    v4-lane-id: "c6m03"
    v4-attempt-id: "attempt0229"
    v4-config-sha: "ba273a28f8edad7cd8a4398506bdea20"
    v4-lane-role: "policy"
spec:
  publishNotReadyAddresses: false
  selector:
    v4-lane-id: "c6m03"
    v4-attempt-id: "attempt0229"
    v4-config-sha: "ba273a28f8edad7cd8a4398506bdea20"
    v4-lane-role: "policy"
  ports:
    - name: policy
      port: 18160
      targetPort: 18160
      protocol: TCP
