apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scripts-configmap.yaml
  - s027-configmap.yaml
  - s027-job.yaml
  - s038-configmap.yaml
  - s038-job.yaml
  - s073-configmap.yaml
  - s073-job.yaml
  - s075-configmap.yaml
  - s075-job.yaml
  - s077-configmap.yaml
  - s077-job.yaml
  - s078-configmap.yaml
  - s078-job.yaml
  - s088-configmap.yaml
  - s088-job.yaml
  - s091-configmap.yaml
  - s091-job.yaml
  - s092-configmap.yaml
  - s092-job.yaml
  - s094-configmap.yaml
  - s094-job.yaml
  - s096-configmap.yaml
  - s096-job.yaml
  - s101-configmap.yaml
  - s101-job.yaml
  - s102-configmap.yaml
  - s102-job.yaml
  - s103-configmap.yaml
  - s103-job.yaml
  - s112-configmap.yaml
  - s112-job.yaml
  - s113-configmap.yaml
  - s113-job.yaml
  - s114-configmap.yaml
  - s114-job.yaml
  - s115-configmap.yaml
  - s115-job.yaml
  - s116-configmap.yaml
  - s116-job.yaml
  - s117-configmap.yaml
  - s117-job.yaml
  - s118-configmap.yaml
  - s118-job.yaml
