apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scripts-configmap.yaml
  - j000-configmap.yaml
  - j000-job.yaml
  - j001-configmap.yaml
  - j001-job.yaml
  - j002-configmap.yaml
  - j002-job.yaml
  - j003-configmap.yaml
  - j003-job.yaml
  - j004-configmap.yaml
  - j004-job.yaml
  - j005-configmap.yaml
  - j005-job.yaml
  - j006-configmap.yaml
  - j006-job.yaml
  - j007-configmap.yaml
  - j007-job.yaml
  - j008-configmap.yaml
  - j008-job.yaml
  - j009-configmap.yaml
  - j009-job.yaml
