apiVersion: v1
kind: Service
metadata:
  name: "v4-c7m31-attempt0592-6d00b703d7-policy"
  namespace: "211247-prod"
  labels:
    v4-lane-id: "c7m31"
    v4-attempt-id: "attempt0592"
    v4-config-sha: "6d00b703d70668409455054100c89d4c"
    v4-lane-role: "policy"
spec:
  publishNotReadyAddresses: false
  selector:
    v4-lane-id: "c7m31"
    v4-attempt-id: "attempt0592"
    v4-config-sha: "6d00b703d70668409455054100c89d4c"
    v4-lane-role: "policy"
  ports:
    - name: policy
      port: 18157
      targetPort: 18157
      protocol: TCP
