apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scripts-configmap.yaml
  - s000-configmap.yaml
  - s000-job.yaml
  - s001-configmap.yaml
  - s001-job.yaml
  - s002-configmap.yaml
  - s002-job.yaml
  - s003-configmap.yaml
  - s003-job.yaml
  - s004-configmap.yaml
  - s004-job.yaml
  - s005-configmap.yaml
  - s005-job.yaml
  - s006-configmap.yaml
  - s006-job.yaml
  - s007-configmap.yaml
  - s007-job.yaml
  - s008-configmap.yaml
  - s008-job.yaml
  - s009-configmap.yaml
  - s009-job.yaml
  - s010-configmap.yaml
  - s010-job.yaml
  - s011-configmap.yaml
  - s011-job.yaml
  - s012-configmap.yaml
  - s012-job.yaml
  - s013-configmap.yaml
  - s013-job.yaml
  - s014-configmap.yaml
  - s014-job.yaml
  - s015-configmap.yaml
  - s015-job.yaml
  - s016-configmap.yaml
  - s016-job.yaml
  - s017-configmap.yaml
  - s017-job.yaml
  - s018-configmap.yaml
  - s018-job.yaml
  - s019-configmap.yaml
  - s019-job.yaml
  - s020-configmap.yaml
  - s020-job.yaml
  - s021-configmap.yaml
  - s021-job.yaml
  - s022-configmap.yaml
  - s022-job.yaml
  - s023-configmap.yaml
  - s023-job.yaml
  - s024-configmap.yaml
  - s024-job.yaml
  - s025-configmap.yaml
  - s025-job.yaml
  - s026-configmap.yaml
  - s026-job.yaml
  - s027-configmap.yaml
  - s027-job.yaml
  - s028-configmap.yaml
  - s028-job.yaml
  - s029-configmap.yaml
  - s029-job.yaml
  - s030-configmap.yaml
  - s030-job.yaml
  - s031-configmap.yaml
  - s031-job.yaml
  - s032-configmap.yaml
  - s032-job.yaml
  - s033-configmap.yaml
  - s033-job.yaml
  - s034-configmap.yaml
  - s034-job.yaml
  - s035-configmap.yaml
  - s035-job.yaml
  - s036-configmap.yaml
  - s036-job.yaml
  - s037-configmap.yaml
  - s037-job.yaml
  - s038-configmap.yaml
  - s038-job.yaml
  - s039-configmap.yaml
  - s039-job.yaml
  - s040-configmap.yaml
  - s040-job.yaml
  - s041-configmap.yaml
  - s041-job.yaml
  - s042-configmap.yaml
  - s042-job.yaml
  - s043-configmap.yaml
  - s043-job.yaml
  - s044-configmap.yaml
  - s044-job.yaml
  - s045-configmap.yaml
  - s045-job.yaml
  - s046-configmap.yaml
  - s046-job.yaml
  - s047-configmap.yaml
  - s047-job.yaml
  - s048-configmap.yaml
  - s048-job.yaml
  - s049-configmap.yaml
  - s049-job.yaml
  - s050-configmap.yaml
  - s050-job.yaml
  - s051-configmap.yaml
  - s051-job.yaml
  - s052-configmap.yaml
  - s052-job.yaml
  - s053-configmap.yaml
  - s053-job.yaml
  - s054-configmap.yaml
  - s054-job.yaml
  - s055-configmap.yaml
  - s055-job.yaml
  - s056-configmap.yaml
  - s056-job.yaml
  - s057-configmap.yaml
  - s057-job.yaml
  - s058-configmap.yaml
  - s058-job.yaml
  - s059-configmap.yaml
  - s059-job.yaml
  - s060-configmap.yaml
  - s060-job.yaml
  - s061-configmap.yaml
  - s061-job.yaml
  - s062-configmap.yaml
  - s062-job.yaml
  - s063-configmap.yaml
  - s063-job.yaml
