apiVersion: v1
kind: Service
metadata:
  name: "v4-c7m31-attempt0598-7332496fbd-policy"
  namespace: "211247-prod"
  labels:
    v4-lane-id: "c7m31"
    v4-attempt-id: "attempt0598"
    v4-config-sha: "7332496fbdc09ad24cf65407e13352a5"
    v4-lane-role: "policy"
spec:
  publishNotReadyAddresses: false
  selector:
    v4-lane-id: "c7m31"
    v4-attempt-id: "attempt0598"
    v4-config-sha: "7332496fbdc09ad24cf65407e13352a5"
    v4-lane-role: "policy"
  ports:
    - name: policy
      port: 18157
      targetPort: 18157
      protocol: TCP
