apiVersion: v1
kind: Service
metadata:
  name: "v4-c7m06-attempt0349-bcaeae43b1-policy"
  namespace: "211247-prod"
  labels:
    v4-lane-id: "c7m06"
    v4-attempt-id: "attempt0349"
    v4-config-sha: "bcaeae43b1f29a851746eaedc25b7ae8"
    v4-lane-role: "policy"
spec:
  publishNotReadyAddresses: false
  selector:
    v4-lane-id: "c7m06"
    v4-attempt-id: "attempt0349"
    v4-config-sha: "bcaeae43b1f29a851746eaedc25b7ae8"
    v4-lane-role: "policy"
  ports:
    - name: policy
      port: 18157
      targetPort: 18157
      protocol: TCP
